### ISSUE TITLE
Fazer com que só seja possível dar Merge depois que algum Reviewer aprovar o Pull Request

### ISSUE THREAD

**Issue by LeoNero** [pagarme/docs.pagar.me#111]
Atualmente, qualquer um que crie uma branch e faça um Pull Request consegue dar merge na Master sem que qualquer pessoa aprove a mudança.

Seria bacana se isso mudasse, pois evita diversos problemas futuros

**Comment by felquis** [comment]
@rodrigoPgSup essa configuração fica nas settings do repo, o ideal serial que qualquer repo da org tivesse a mesma config.

**Comment by rodrigoPgSup** [comment]
Olá @LeoNero e @felquis , sim vocês estão certos. Vou dar uma olhada nessa config.

**Comment by henriquekano** [comment]
@rodrigoPgSup: any updates regarding this issue?

**Comment by mccraveiro** [comment]
Fechando esta issue pois o projeto foi descontinuado e a documentação movida para o [readme.io](https://docs.pagar.me/).
Sugestões podem ser enviadas diretamente através de "Suggested edits" na própria documentação.
